**Data Science and Machine Learning course - Batch-302**

**Assignment-3 - Data Pre-Processing**

**Submission Date: 26/01/2025**

**General Instructions for Assignment submission**
- **Please zip all the files** - Python code with results, screenshots, text file, etc. Any file please zip all, and upload as a single file.
- That zip file's name, keep it based on this template "**dsmlbatch302_ASM3_<your_firstname>_<your_initial>.zip**"
- Upload File option will be present after clicking the "Attempt Now" button in the Assignments page
- For clarity about the Assignment, **refer the class video recordings** or ask questions during the next session

--------------------------------

In [1]:
import pandas as pd

In [24]:
df = pd.read_csv('Sleep_Efficiency.csv')

In [25]:
df.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      452 non-null    int64
 1   Age                     452 non-null    int64
 2   Gender                  452 non-null    object
 3   Bedtime                 452 non-null    object
 4   Wakeup time             452 non-null    object
 5   Sleep duration          452 non-null    float64
 6   Sleep efficiency        452 non-null    float64
 7   REM sleep percentage    452 non-null    int64
 8   Deep sleep percentage   452 non-null    int64
 9   Light sleep percentage  452 non-null    int64
 10  Awakenings              432 non-null    float64
 11  Caffeine consumption    427 non-null    float64
 12  Alcohol consumption     438 non-null    float64
 13  Smoking status          452 non-null    object
 14  Exercise frequency      446 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 53.1+ KB

**Q1)** In "Caffeine consumption" column, **delete rows with missing values**, and print the output

In [29]:
df_1 = df.dropna(subset=["Caffeine consumption"])

In [31]:
df_1

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,447,23,Male,2021-04-21 00:00:00,2021-04-21 07:00:00,7.0,0.50,15,40,45,2.0,0.0,4.0,Yes,NaN
447,448,27,Female,2021-11-13 22:00:00,2021-11-13 05:30:00,7.5,0.91,22,57,21,0.0,0.0,0.0,No,5.0
448,449,52,Male,2021-03-31 21:00:00,2021-03-31 03:00:00,6.0,0.74,28,57,15,4.0,25.0,0.0,No,3.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0

In [32]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 427 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      427 non-null    int64
 1   Age                     427 non-null    int64
 2   Gender                  427 non-null    object
 3   Bedtime                 427 non-null    object
 4   Wakeup time             427 non-null    object
 5   Sleep duration          427 non-null    float64
 6   Sleep efficiency        427 non-null    float64
 7   REM sleep percentage    427 non-null    int64
 8   Deep sleep percentage   427 non-null    int64
 9   Light sleep percentage  427 non-null    int64
 10  Awakenings              408 non-null    float64
 11  Caffeine consumption    427 non-null    float64
 12  Alcohol consumption     413 non-null    float64
 13  Smoking status          427 non-null    object
 14  Exercise frequency      421 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 53.4+ KB

**Q2)** In "Gender" column, replace the words "Female" and "Male" **as "F" and "M"**.

In [37]:
df_1 = df_1.copy()
df_1["Gender"] = df_1["Gender"].replace({"Female": "F","Male": "M"},)

In [40]:
df_1["Wakeup time"] = pd.to_datetime(df_1["Wakeup time"], format="mixed")

In [41]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 427 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      427 non-null    int64
 1   Age                     427 non-null    int64
 2   Gender                  0 non-null      object
 3   Bedtime                 427 non-null    object
 4   Wakeup time             427 non-null    datetime64[ns]
 5   Sleep duration          427 non-null    float64
 6   Sleep efficiency        427 non-null    float64
 7   REM sleep percentage    427 non-null    int64
 8   Deep sleep percentage   427 non-null    int64
 9   Light sleep percentage  427 non-null    int64
 10  Awakenings              408 non-null    float64
 11  Caffeine consumption    427 non-null    float64
 12  Alcohol consumption     413 non-null    float64
 13  Smoking status          427 non-null    object
 14  Exercise frequency      421 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(5), object(3)
memory usage: 53.4+ KB

In [43]:
df_1.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,None,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,None,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,None,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,None,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,None,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

**Q4)** Create a new column called as **"duration_category" containing data** based on the following conditions:
- If the "Sleep duration" is greater than or equal to 7.0, mark that row's **"duration_category" as 1**.
- If the "Sleep duration" is less than 7.0, mark that row's **"duration_category" as 0**.

In [44]:

def sleep_efficiency(x):
    if (x >= 0.8):
        return(1)  

    elif(x < 0.8):
        return(0)

In [45]:
df_1["Sleep efficiency"].map(sleep_efficiency)

0      1
1      0
2      1
3      0
4      0
      ..
446    0
447    1
448    0
450    0
451    0
Name: Sleep efficiency, Length: 427, dtype: int64

In [46]:
#df.loc[:,"duration_category"] = df["Sleep efficiency"].map(sleep_efficiency)
df_1["duration_category"] = df_1["Sleep efficiency"].map(sleep_efficiency)

In [47]:
df_1.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency,duration_category
0,1,65,None,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0,1
1,2,69,None,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0,0
2,3,40,None,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0,1
3,4,40,None,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0,0
4,5,57,None,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0,0

In [48]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 427 entries, 0 to 451
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      427 non-null    int64
 1   Age                     427 non-null    int64
 2   Gender                  0 non-null      object
 3   Bedtime                 427 non-null    object
 4   Wakeup time             427 non-null    datetime64[ns]
 5   Sleep duration          427 non-null    float64
 6   Sleep efficiency        427 non-null    float64
 7   REM sleep percentage    427 non-null    int64
 8   Deep sleep percentage   427 non-null    int64
 9   Light sleep percentage  427 non-null    int64
 10  Awakenings              408 non-null    float64
 11  Caffeine consumption    427 non-null    float64
 12  Alcohol consumption     413 non-null    float64
 13  Smoking status          427 non-null    object
 14  Exercise frequency      421 non-null    float64
 15  duration_category       427 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(6), object(3)
memory usage: 56.7+ KB

**Q5)** **Group by** the column "duration_category" and **find the counts**

In [49]:
df_1.groupby(by="duration_category")

In [50]:
df_1.groupby(by="duration_category").count()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
duration_category,,,,,,,,,,,,,,,
0,184,184,0,184,184,184,184,184,184,184,177,184,178,184,182
1,243,243,0,243,243,243,243,243,243,243,231,243,235,243,239

In [52]:
df_1.shape

(427, 16)